presentation/Controllers/AttachemntController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using Core;
using Business;
using Business.Models;
using Business.Managers;
using System.IO;

namespace presentation.Controllers
{
    public class AttachmentController : XController
    {
        /// <summary>
        /// 附件上传
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Upload()
        {
            try
            {
                var description = Helper.Trim(Request["description"]);

                HttpFileCollectionBase files = Request.Files;
                //上传实际中每次只上传一个文件
                HttpPostedFileBase file = files[files.AllKeys[0]];

                Stream stream = file.InputStream;

                string fileName = file.FileName;
                //ie下在通过form上传的时候的文件名会包含路径
                int index = fileName.LastIndexOf('\\');
                if (index != -1)
                {
                    fileName = fileName.Substring(index + 1);
                }
                var url = AttachmentManager.Instance.UploadAttachment(fileName, description, stream);//
                
                //Attachment result = retValue.Value;
                return Json(url);
            }
            catch (Exception e)
            {
                return Json(new ErrorCode(e.Message));
            }
        }

        /// <summary>
        /// 附件下载
        /// </summary>
        /// <returns></returns>
        //public FileStreamResult DownLoad()
        //{
        //    int id = Helper.ToInt(Request["id"]);
        //    var retValue = AppHost.Current.Resolve<IFoundationService>().GetAttachmentById(id, true);
        //    if (!retValue.IsSuccess)
        //    {
        //        throw retValue.ToBusinessException();
        //    }
        //    return File(new FileStream(retValue.Value.FullPath, FileMode.Open), "application/octet-stream", retValue.Value.Name);
        //}

    }
}

presentation/Controllers/HistoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using Core;
using Business;
using Business.Models;
using Business.Managers;
using System.Data.Entity.Validation;

namespace presentation.Controllers
{
    public class HistoryController : XController
    {
        /// <summary>
        /// 恢复某版本历史记录
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Recovery()
        {
            if (!Request.IsAuthenticated)
            {
                return Json(NestedErrorCodes.NotAuthenticated);
            }
            
            int id = Helper.ToInt(Request["id"]);
            var history = HistoryManager.Instance.Get(id);
            if (history == null)
            {
                return Json(new ErrorCode(string.Format("id 为 {0} 历史记录不存在", id)));
            }
            var presentation = PresentationManager.Instance.Get(history.PresentationId);
            if (presentation == null)
            {
                return Json(new ErrorCode(string.Format("id 为 {0} 文件不存在", history.PresentationId)));
            }

            var returnValue = PresentationManager.Instance.SaveWithHistory(history.Raw, presentation);
            if (!returnValue.Successed)
            {
                return Json(returnValue.ErrorCode);
            }
            return Json(string.Empty);
        }
                    
        
        public ActionResult Get()
        {
            if (!Request.IsAuthenticated)
            {
                return Json(NestedErrorCodes.NotAuthenticated);
            }

            int id = Helper.ToInt(Request["id"]);
            var result = HistoryManager.Instance.Get(id);
            if (result == null)
            {
                return Json(new ErrorCode("当前文件不存在"));
            }

            return Json(result, JsonRequestBehavior.AllowGet);
        }

        
        public ActionResult All()
        {
            if (!Request.IsAuthenticated)
            {
                return Json(NestedErrorCodes.NotAuthenticated);
            }
            int presentationId = Helper.ToInt(Request["id"]);

            var result = HistoryManager.Instance.Where(h => h.PresentationId == presentationId)
                .OrderByDescending(h => h.LastUpdateTime);

            return Json(result, JsonRequestBehavior.AllowGet);
        }
    }
}

presentation/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using WebMatrix.WebData;
using Business.Managers;

namespace presentation.Controllers
{
    public class HomeController : XController
    {
        public ActionResult Index()
        {
            if (Request.IsAuthenticated)
            {
                var user = AccountManager.Instance.FirstOrDefault(a => a.Name == User.Identity.Name);

                ViewBag.User = user;
                ViewBag.returnUrl = "/home";
            }
            else
            {
                
            }
            return View();
        }
    }
}

presentation/Controllers/PresentationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using Core;
using Business;
using Business.Models;
using Business.Managers;

namespace presentation.Controllers
{
    public class PresentationController : XController
    {
        string defaultName = "未命名";
        string defaultRaw = "[{\"transition\":\"zoom\",\"content\":\"# 请输入标题\", \"key\":\"1\"}]";

        [HttpPost]
        public ActionResult Add()
        {
            if (!Request.IsAuthenticated)
            {
                return Json(NestedErrorCodes.NotAuthenticated);
            }

            string name = Helper.Trim(Request["name"]);
            int folderId = Helper.ToInt(Request["folderId"]);

            var model = new Presentation()
            {
                Name = defaultName,
                UserId = this.CurrentUser.Id,
                Raw = defaultRaw,
                FolderId = folderId
            };

            var returnValue = PresentationManager.Instance.Add(model);
            if (!returnValue.Successed)
            {
                return Json(returnValue.ErrorCode);
            }
            return Json(returnValue.Value.Id);
        }

        [HttpPost]
        public ActionResult Save()
        {
            if (!Request.IsAuthenticated)
            {
                return Json(NestedErrorCodes.NotAuthenticated);
            }

            int id = Helper.ToInt(Request["id"]);
            string raw = Helper.Trim(Request["raw"]);
            string name = Helper.Trim(Request["name"]);

            var model = PresentationManager.Instance.Get(id);
            if (model == null)
            {
                return Json(new ErrorCode(string.Format("id 为 {0} 文件不存在", id)));
            }

            if (!string.IsNullOrWhiteSpace(name))
            {
                model.Name = name;
            }

            ReturnValue<Presentation> returnValue;
            if (string.IsNullOrWhiteSpace(raw))
            {
                returnValue = PresentationManager.Instance.Update(model);
            }
            else
            {
                returnValue = PresentationManager.Instance.SaveWithHistory(raw, model);
            }
            if (!returnValue.Successed)
            {
                return Json(returnValue.ErrorCode);
            }
            return Json(string.Empty);
        }

        public ActionResult Get()
        {
            if (!Request.IsAuthenticated)
            {
                return Json(NestedErrorCodes.NotAuthenticated);
            }

            int id = Helper.ToInt(Request["id"]);
            var user = AccountManager.Instance.FirstOrDefault(a => a.Name == User.Identity.Name);
            var result = PresentationManager.Instance.FirstOrDefault(p => p.Id == id);

            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public ActionResult All()
        {
            if (!Request.IsAuthenticated)
            {
                return Json(NestedErrorCodes.NotAuthenticated);
            }

            var result = PresentationManager.Instance.Where(p => p.UserId == this.CurrentUser.Id);

            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Recent()
        {
            if (!Request.IsAuthenticated)
            {
                return Json(NestedErrorCodes.NotAuthenticated);
            }

            var user = AccountManager.Instance.FirstOrDefault(a => a.Name == User.Identity.Name);
            var result = PresentationManager.Instance.Where(p => p.UserId == user.Id)
                .OrderByDescending(p => p.LastUpdateTime)
                .Take(5);

            return Json(result , JsonRequestBehavior.AllowGet);
        }
    }
}

presentation/Views/Home/About.cshtml
@{
    ViewBag.Title = "关于";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<article>
    <p>
        使用此区域可提供附加信息。
    </p>

    <p>
        使用此区域可提供附加信息。
    </p>

    <p>
        使用此区域可提供附加信息。
    </p>
</article>

<aside>
    <h3>副标题</h3>
    <p>
        使用此区域可提供附加信息。
    </p>
    <ul>
        <li>@Html.ActionLink("主页", "Index", "Home")</li>
        <li>@Html.ActionLink("关于", "About", "Home")</li>
        <li>@Html.ActionLink("联系方式", "Contact", "Home")</li>
    </ul>
</aside>

presentation/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "联系方式";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<section class="contact">
    <header>
        <h3>电话</h3>
    </header>
    <p>
        <span class="label">主要:</span>
        <span>425.555.0100</span>
    </p>
    <p>
        <span class="label">下班后:</span>
        <span>425.555.0199</span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>电子邮件</h3>
    </header>
    <p>
        <span class="label">支持:</span>
        <span><a href="mailto:Support@example.com">Support@example.com</a></span>
    </p>
    <p>
        <span class="label">营销:</span>
        <span><a href="mailto:Marketing@example.com">Marketing@example.com</a></span>
    </p>
    <p>
        <span class="label">常规:</span>
        <span><a href="mailto:General@example.com">General@example.com</a></span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>地址</h3>
    </header>
    <p>
        One Microsoft Way<br />
        Redmond, WA 98052-6399
    </p>
</section>

presentation/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Web Presentation";

    var user = ViewBag.User;
    var id = 0;
    var name = string.Empty;
    var description = string.Empty;
    if(user != null){
        id = user.Id;
        name = user.Name.Replace("'", "\\'");
        description = user.Description.Replace("'", "\\'");
    }
}

@section Styles {
    @Styles.Render("~/Content/themes/main")
}

<div id="app"></div>

@section Scripts {
    <script>
        var _config = {
            user: {
                id: @id,
                name: '@Html.Raw(name)',
                description: '@Html.Raw(description)',
                isAuthenticated: @(Request.IsAuthenticated ? "true" : "false"),
                
                signUp: '@Url.Action("Register", "Account")',
                signIn: '@Url.Action("Login", "Account")',
                save: '@Url.Action("Update", "Account")',
            },


            add: '@Url.Action("Add", "Presentation")',
            save: '@Url.Action("Save", "Presentation")',
            get: '@Url.Action("Get", "Presentation")',
            all: '@Url.Action("All", "Presentation")',
            recent: '@Url.Action("Recent", "Presentation")',
            history: '@Url.Action("All", "History")',
            upload: '@Url.Action("Upload", "Attachment")'
        };
    </script>
    @Scripts.Render("~/bundles/app")
}